id: I6FCD8881
legacy_id: P010346
ocr_import_info:
  bdrc_scan_id: W24769
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T00:16:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:40:04.066633+00:00'
last_modified: 2022-09-02 13:47:46.627469
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W24769
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW24769
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ་པ།
  author: དགེ་འདུན་གྲུབ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7615993485675513
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I3843:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3843
      total_pages: 858
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3843.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.7167016605832564
    legacy_id: v001
  I3846:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3846
      total_pages: 754
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3846.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8200292097867334
    legacy_id: v004
  I3844:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3844
      total_pages: 918
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3844.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7057914559734636
    legacy_id: v002
  I6320:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6320
      total_pages: 752
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I6320.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.8077049392369198
    legacy_id: v006
  I3845:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3845
      total_pages: 1232
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3845.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7570270558311295
    legacy_id: v003
  I3847:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3847
      total_pages: 804
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3847.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7722530025974821
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
