id: P010346
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W24769
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ་པ
  author: ''
  volumes:
    1b930e33bc19490faf28a7ea3edc4f1c:
      image_group_id: I3843
      title: ''
      volume_number: 1
      total_pages: 858
      base_file: v001.txt
    367b4c8dafa145aeac2566b8e196c6dd:
      image_group_id: I3844
      title: ''
      volume_number: 2
      total_pages: 918
      base_file: v002.txt
    0f2e8668f07d488bb9ed4b231bef2e49:
      image_group_id: I3845
      title: ''
      volume_number: 3
      total_pages: 1232
      base_file: v003.txt
    4e0c346cc0344f7fa688512f72cf7a00:
      image_group_id: I3846
      title: ''
      volume_number: 4
      total_pages: 754
      base_file: v004.txt
    212f61411ddf4880a5b02e5baf34dd31:
      image_group_id: I3847
      title: ''
      volume_number: 5
      total_pages: 804
      base_file: v005.txt
    c8525876431a4f2d8f21da9ffbe9fd56:
      image_group_id: I6320
      title: ''
      volume_number: 6
      total_pages: 752
      base_file: v006.txt
